import type { Metadata } from "next";
import "./globals.css";
import { TheHeader } from "@/components/TheHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <TheHeader />
        <main>{children}</main>
      </body>
    </html>
  );
}
